// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiClientes.Models
{
    public partial class ContatosClientes
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("dbo.DadosClientesId")]
        [ForeignKey("DboDadosClientes")]
        public int? DboDadosClientesId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Nome { get; set; }
        [StringLength(11)]
        [Unicode(false)]
        public string Telefone { get; set; }
    }
}