// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ApiClientes.Models
{
    public partial class DadosClientes
    {
        [Key]
        public int Id { get; set; }
        public string Cpf { get; set; }

        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Nome { get; set; }
        public string Celular { get; set; }
        public string Cep { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string Endereco { get; set; }
        public int Numero { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Complemento { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string Email { get; set; }
        public string EstadoCivil { get; set; }
    }
}